apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    #pod 에 설정되는 컨테이너 설정
    spec:
      containers:
        - name: user-service-container
          image: {{ .Values.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081