#서비스 변경감지용 주석
server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, beans













